### ISSUE TITLE
[Query] Is there way the component can support live transcribing.

### ISSUE THREAD

**Issue by e0lithic** [B4PT0R/streamlit-mic-recorder#2]
Hi,

Great component, works smoothly out of the box. I was wondering if there is a way to use this component to perform pseudo live transcriptions. 

For example, a programmable duration or a callback which takes the audio file and splits on the basis of silence etc, so that it can continue recording while the initial chunks can be processed and displayed to the user for live feedback.

I am still new to this field and hence not completely sure if that is even possible, would be great if you could share your thoughts or pointers for the same.

Thanks

**Comment by B4PT0R** [comment]
Hello!

Given the constraints of streamlit runtime, what you're asking for, though not plainly impossible, would require a serious and complex refactor of the code.

The main issue here is that the python backend doesn't receive outputs from the React component in a real time fashion. The python script needs to be executed from top to bottom to first render the component, and then rerun another loop to receive returned output from the component. Receiving outputs from the component in a streamed fashion would require to loop the script as many times as the number of outputs you want to receive on the python side. For a simple app focusing only on speech recognition, this could be fine, but for a more complex app, with a lot of widgets on screen having to rerender on every rerun, too many reruns would be too resource consuming.

This would also require to implement some audio analysis to detect silence directly in the front-end React component (in browser computations). Which can be tricky to achieve.

The timer solution might be good enough (avoiding too many reruns, and involving no audio analysis on the front-end side), but it would likely cut sentences in the middle, and give poor results with speech recognition APIs.
 
So I'm afraid there is no straightforward way to make this work in a streamed fashion given streamlit constraints, though definitely not impossible.

**Comment by e0lithic** [comment]
Thank you for the insightful answer. I'll reopen this issue if in future I come across implementing this as a feature.
