### ISSUE TITLE
st.session_state has no attribute "_last_audio_id".

### ISSUE THREAD

**Issue by Irfan-Ahmad-byte** [B4PT0R/streamlit-mic-recorder#3]
Hey,
i'm trying to record audio with this package and getting the following error:
AttributeError: st.session_state has no attribute "_last_audio_id". Did you forget to initialize it?

the code snippet:
```if ((query:= st.chat_input("How can I assist you?", key="query"))
            or (audio:=mic_recorder(
                    start_prompt="Start recording",
                    stop_prompt="Stop recording", 
                    key='audio',
                ))):
            
            if audio:
                query = self.chain.transcribe(audio['bytes'])
```

the error:
..................app.py", line 38, in ask
    or (audio:=mic_recorder(
  File "/home/user/Documents/venv/lib/python3.8/site-packages/streamlit_mic_recorder/__init__.py", line 30, in mic_recorder
    if id>state._last_audio_id or just_once==False:
  File "/home/irfan/Documents/venv/lib/python3.8/site-packages/streamlit/runtime/state/session_state_proxy.py", line 121, in __getattr__
    raise AttributeError(_missing_attr_error_message(key))
AttributeError: st.session_state has no attribute "_last_audio_id". Did you forget to initialize it? More info: https://docs.streamlit.io/library/advanced-features/session-state#initialization

**Comment by Irfan-Ahmad-byte** [comment]
and I resolved this error by manually initializing the attribute.

`    st.session_state._last_audio_id = 0
`

**Comment by B4PT0R** [comment]
Hello,

Yeah, my bad. I initialized this state variable out of the mic recorder function in the module, resulting in this error, as the code at module level isn't executed when importing just the function.
I've made the required changes and added the possibility to pass a callback on sound reception.
I'll update the python package tomorrow on PyPi so stay tuned.

Cheers!

Baptiste

**Comment by Irfan-Ahmad-byte** [comment]
great, thanks.

**Comment by B4PT0R** [comment]
Just posted the new version on PyPi.
